gcloud:
  projectId: 
micronaut:
  server:
    port: 8080
  openapi:
    enabled: true
  application:
    name: starter
  http:
    client:
      read-timeout: 120s
      connection-pool-idle-timeout: 30s
      connection-pool-max-connections: 50
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**

logger:
  levels:
    com.epipoli.starter: INFO
    com.epipoli.commons.datastore: INFO
